### ISSUE TITLE
Unpublish 0.4.0

### ISSUE THREAD

**Issue by mrhyde** [vitkarpov/grunt-nunjucks-2-html#34]
Since this release will guarantee a lot of problem to current users i'm suggesting we [unpublish](https://docs.npmjs.com/cli/unpublish) it and republish under 1.0.0 version

Small reminder why:
1. NPM by default uses `^` (caret) for version targeting
2. We bumped minore version
3. All users will get it regardless ready are they for ES2015 (hate this name) or not
4. A lot of issues and broken builds :disappointed:

**Comment by ArmorDarks** [comment]
:+1:

**Comment by ArmorDarks** [comment]
I also suggest to mark us 0.4.0 that commit:

https://github.com/vitkarpov/grunt-nunjucks-2-html/commit/125d8c4443a0b55aadcad330c75f66654e51a25c

it introduces some improvements, but doesn't require node higher then 0.8.0, which were used as required before

All commits after that point introducing ES6

And finally, we have to bump major version here instead of 0.3.0 too due to changed behavior of autoescaping

**Comment by vitkarpov** [comment]
I unpublished it yesterday, when made new 1.0.0 version. Try to install 0.4.0 now:

```
npm ERR! version not found: grunt-nunjucks-2-html@0.4.0
```

**Comment by vitkarpov** [comment]
Check out the new version

**Comment by mrhyde** [comment]
Great! But you still want to remove release and tag on github repo ;)

**Comment by vitkarpov** [comment]
Done! :) Thanks

**Comment by mrhyde** [comment]
:+1: 
I'm closing this then.
